//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2LinkXamarin.WebServiceClients
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/M2Link.Entities")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private System.Guid IdField;
        
        private string MdpField;
        
        private string NomField;
        
        private string PrenomField;
        
        private string PseudoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mdp
        {
            get
            {
                return this.MdpField;
            }
            set
            {
                this.MdpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom
        {
            get
            {
                return this.PrenomField;
            }
            set
            {
                this.PrenomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudo
        {
            get
            {
                return this.PseudoField;
            }
            set
            {
                this.PseudoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="M2LinkXamarin.WebServiceClients.IWSUser")]
    public interface IWSUser
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/DoWork", ReplyAction="http://tempuri.org/IWSUser/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/DoWork", ReplyAction="http://tempuri.org/IWSUser/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/Validate", ReplyAction="http://tempuri.org/IWSUser/ValidateResponse")]
        M2LinkXamarin.WebServiceClients.User Validate(string login, string mdp);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/Validate", ReplyAction="http://tempuri.org/IWSUser/ValidateResponse")]
        System.IAsyncResult BeginValidate(string login, string mdp, System.AsyncCallback callback, object asyncState);
        
        M2LinkXamarin.WebServiceClients.User EndValidate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/VerifyExistPseudo", ReplyAction="http://tempuri.org/IWSUser/VerifyExistPseudoResponse")]
        bool VerifyExistPseudo(string Pseudo);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/VerifyExistPseudo", ReplyAction="http://tempuri.org/IWSUser/VerifyExistPseudoResponse")]
        System.IAsyncResult BeginVerifyExistPseudo(string Pseudo, System.AsyncCallback callback, object asyncState);
        
        bool EndVerifyExistPseudo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/AddUser", ReplyAction="http://tempuri.org/IWSUser/AddUserResponse")]
        void AddUser(M2LinkXamarin.WebServiceClients.User User);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/AddUser", ReplyAction="http://tempuri.org/IWSUser/AddUserResponse")]
        System.IAsyncResult BeginAddUser(M2LinkXamarin.WebServiceClients.User User, System.AsyncCallback callback, object asyncState);
        
        void EndAddUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/GetListUser", ReplyAction="http://tempuri.org/IWSUser/GetListUserResponse")]
        M2LinkXamarin.WebServiceClients.User[] GetListUser();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/GetListUser", ReplyAction="http://tempuri.org/IWSUser/GetListUserResponse")]
        System.IAsyncResult BeginGetListUser(System.AsyncCallback callback, object asyncState);
        
        M2LinkXamarin.WebServiceClients.User[] EndGetListUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/ModifyUser", ReplyAction="http://tempuri.org/IWSUser/ModifyUserResponse")]
        void ModifyUser(M2LinkXamarin.WebServiceClients.User user);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/ModifyUser", ReplyAction="http://tempuri.org/IWSUser/ModifyUserResponse")]
        System.IAsyncResult BeginModifyUser(M2LinkXamarin.WebServiceClients.User user, System.AsyncCallback callback, object asyncState);
        
        void EndModifyUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/GetUser", ReplyAction="http://tempuri.org/IWSUser/GetUserResponse")]
        M2LinkXamarin.WebServiceClients.User GetUser(System.Guid myId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/GetUser", ReplyAction="http://tempuri.org/IWSUser/GetUserResponse")]
        System.IAsyncResult BeginGetUser(System.Guid myId, System.AsyncCallback callback, object asyncState);
        
        M2LinkXamarin.WebServiceClients.User EndGetUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSUser/GetNbFollowers", ReplyAction="http://tempuri.org/IWSUser/GetNbFollowersResponse")]
        int GetNbFollowers(System.Guid myId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWSUser/GetNbFollowers", ReplyAction="http://tempuri.org/IWSUser/GetNbFollowersResponse")]
        System.IAsyncResult BeginGetNbFollowers(System.Guid myId, System.AsyncCallback callback, object asyncState);
        
        int EndGetNbFollowers(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSUserChannel : M2LinkXamarin.WebServiceClients.IWSUser, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSUserClient : System.ServiceModel.ClientBase<M2LinkXamarin.WebServiceClients.IWSUser>, M2LinkXamarin.WebServiceClients.IWSUser
    {
        
        public WSUserClient()
        {
        }
        
        public WSUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WSUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WSUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void DoWork()
        {
            base.Channel.DoWork();
        }
        
        public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        public void EndDoWork(System.IAsyncResult result)
        {
            base.Channel.EndDoWork(result);
        }
        
        public M2LinkXamarin.WebServiceClients.User Validate(string login, string mdp)
        {
            return base.Channel.Validate(login, mdp);
        }
        
        public System.IAsyncResult BeginValidate(string login, string mdp, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginValidate(login, mdp, callback, asyncState);
        }
        
        public M2LinkXamarin.WebServiceClients.User EndValidate(System.IAsyncResult result)
        {
            return base.Channel.EndValidate(result);
        }
        
        public bool VerifyExistPseudo(string Pseudo)
        {
            return base.Channel.VerifyExistPseudo(Pseudo);
        }
        
        public System.IAsyncResult BeginVerifyExistPseudo(string Pseudo, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginVerifyExistPseudo(Pseudo, callback, asyncState);
        }
        
        public bool EndVerifyExistPseudo(System.IAsyncResult result)
        {
            return base.Channel.EndVerifyExistPseudo(result);
        }
        
        public void AddUser(M2LinkXamarin.WebServiceClients.User User)
        {
            base.Channel.AddUser(User);
        }
        
        public System.IAsyncResult BeginAddUser(M2LinkXamarin.WebServiceClients.User User, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginAddUser(User, callback, asyncState);
        }
        
        public void EndAddUser(System.IAsyncResult result)
        {
            base.Channel.EndAddUser(result);
        }
        
        public M2LinkXamarin.WebServiceClients.User[] GetListUser()
        {
            return base.Channel.GetListUser();
        }
        
        public System.IAsyncResult BeginGetListUser(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetListUser(callback, asyncState);
        }
        
        public M2LinkXamarin.WebServiceClients.User[] EndGetListUser(System.IAsyncResult result)
        {
            return base.Channel.EndGetListUser(result);
        }
        
        public void ModifyUser(M2LinkXamarin.WebServiceClients.User user)
        {
            base.Channel.ModifyUser(user);
        }
        
        public System.IAsyncResult BeginModifyUser(M2LinkXamarin.WebServiceClients.User user, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginModifyUser(user, callback, asyncState);
        }
        
        public void EndModifyUser(System.IAsyncResult result)
        {
            base.Channel.EndModifyUser(result);
        }
        
        public M2LinkXamarin.WebServiceClients.User GetUser(System.Guid myId)
        {
            return base.Channel.GetUser(myId);
        }
        
        public System.IAsyncResult BeginGetUser(System.Guid myId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetUser(myId, callback, asyncState);
        }
        
        public M2LinkXamarin.WebServiceClients.User EndGetUser(System.IAsyncResult result)
        {
            return base.Channel.EndGetUser(result);
        }
        
        public int GetNbFollowers(System.Guid myId)
        {
            return base.Channel.GetNbFollowers(myId);
        }
        
        public System.IAsyncResult BeginGetNbFollowers(System.Guid myId, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetNbFollowers(myId, callback, asyncState);
        }
        
        public int EndGetNbFollowers(System.IAsyncResult result)
        {
            return base.Channel.EndGetNbFollowers(result);
        }
    }
}
